### ISSUE TITLE
Fix cheap thrills cuisine

### ISSUE THREAD

**Issue by oseparovic** [oseparovic/comic_selectors#112]

**Comment by kc2cbd** [comment]
No longer published as of 2018
https://www.dailycartoonist.com/index.php/2021/02/10/cheap-thrills-cuisine-chef-peppis-first-and-last/
another article https://grubbits.com/the-thrill-is-not-gone-cheap-thrills-cuisine/
per that article it is not listed in there comics http://syndication.andrewsmcmeel.com/comics/list
There is a pinterest page https://www.pinterest.com/toneerhianrose/recipes-cheap-thrills-cuisine-comic-strip/
