### ISSUE TITLE
Fix Arlo and Janis link

### ISSUE THREAD

**Issue by DeeMac512** [oseparovic/comic_selectors#117]
The link for Arlo and Janis is now showing Andertoons comics

**Comment by oseparovic** [comment]
This is a bug in the app itself. Make sure your app is up to date and then:

1. Click on Arlo and Janis
2. Click on the 3dot menu in the top right corner
3. Click "reset starting point"
4. Click "dew it"
5. You should be back on the first page of Arlo and Janis

If this doesn't work you'll have to clear your app storage to fix the issue (varies by operating system version)

1. Open you Android Settings app
2. Click on apps
3. Click on pageflip
4. Click on storage
5. (this will delete all your browsing history and favourites!) Clear storage

**Comment by DeeMac512** [comment]
I tried deleting the cache and then the app data but to no avail.  Finally
I removed the app and reinstalled it.  I had to reselect the comics I
wanted to see but it is working perfectly now.

thank you for your time.
Dave
