### ISSUE TITLE
Fix thieves can't

### ISSUE THREAD

**Issue by oseparovic** [oseparovic/comic_selectors#120]

**Comment by kc2cbd** [comment]
I believe I fixed this.

**Comment by oseparovic** [comment]
Something still wrong with this one

**Comment by kc2cbd** [comment]
Some of the images are .jpg and some are .png which I believe the app is having issues with.

**Comment by kc2cbd** [comment]
The home page is doing this weird download thing. I believe there hasn't been a new strip since July or August 2021

**Comment by oseparovic** [comment]
site no longer exists
