### ISSUE TITLE
Penny arcade is broken

### ISSUE THREAD

**Issue by comradechrome** [oseparovic/comic_selectors#129]
![Screenshot_20220427-092836](https://user-images.githubusercontent.com/11307967/165567497-cff9a969-4b11-47b1-8144-347a951cf49e.png)

Haven't used the app in a long while, so no idea when this started

**Comment by comradechrome** [comment]
I've tried reinstalling it from the play store, no luck. I'm on a pixel 6

**Comment by oseparovic** [comment]
site format changed in a way we can no longer support. Flagged as unsupported
