### ISSUE TITLE
Sherman's Lagoon by Jim Toomey moved to GoComics from Comic Kingdom

### ISSUE THREAD

**Issue by SmilingTexan** [oseparovic/comic_selectors#130]
The new address for Sherman's Lagoon is https://www.gocomics.com/shermanslagoon/'year'/'month'/'date' and should be supported under the Go Comics type.

**Comment by kc2cbd** [comment]
Can fix but the first comic on Go Comics is May 1, 2022

**Comment by SmilingTexan** [comment]
I believe that was the first day it appeared on GoComics.

**Comment by kc2cbd** [comment]
Yes it is.
