### ISSUE TITLE
How to handle comics in list style (no prev/next buttons) 

### ISSUE THREAD

**Issue by bnichs** [oseparovic/comic_selectors#135]
I want to add https://pizzacakecomic.com/ which appears to just be a tumblr site. The setup is such that when you select the latest comic, you can't go next/prev/random, you can only either see the comic or see a list of all comics. Is there a way to add comics like this?

**Comment by oseparovic** [comment]
Unfortunately the app cannot support this format of comics. Aside from the formatting a big issue is that tumblr feed type comic sites almost always have some form lazy loading - more comics are only loaded only when you scroll. The app cannot emulate this behaviour while also remembering and returning to previous position.

Apologies
