### ISSUE TITLE
Many comics not working 

### ISSUE THREAD

**Issue by ShaNagba** [oseparovic/comic_selectors#146]

**Comment by MarkH58** [comment]
Having the same problem. BC, Garfield, Calvin & Hobbs plus many other failing to open. This has been going on for the last couple of days.

**Comment by ShaNagba** [comment]
Thanks for the heads up.

**Comment by MarkH58** [comment]
Thank you for taking the time to reply.👍

Mark

**Comment by oseparovic** [comment]
gocomics is back up and their hosted comics like Non Sequitor are working again. Marking this issue as closed
