### ISSUE TITLE
Dilbert Classics not working 

### ISSUE THREAD

**Issue by houseofbugs** [oseparovic/comic_selectors#155]
Hi there. Today as I was reading through the Dilbert Classics they all disappeared and won't load. I think it's because they aren't available on GoComics anymore.

**Comment by oseparovic** [comment]
Dilbert creator has made some publicly racist and hateful comments and has been dropped by a huge number of publications including gocomics and arcamax. https://www.bostonherald.com/2023/02/26/media-drop-dilbert-after-creators-black-hate-group-remark/

**Comment by houseofbugs** [comment]
I really don't care, I just wanted to read some comics. The comics are not racist.... One more fun thing ruined by the woke mob.

**Comment by houseofbugs** [comment]
I really don't care, I just wanted to read some comics. The comics are not racist.... One more fun thing ruined by the woke mob.

**Comment by houseofbugs** [comment]
Are they're any other places that host the classic ones so we can still read them?

**Comment by oseparovic** [comment]
If you can find one feel free to submit a request. The official dilbert site is a scroll to load format which doesn't work with this app unfortunately
