### ISSUE TITLE
Hagar the Horrible

### ISSUE THREAD

**Issue by Dalemal** [oseparovic/comic_selectors#161]
Hagar the Horrible is not working

**Comment by oseparovic** [comment]
Can you provide more details? I'm not currently seeing any issues with navigation or image loading

**Comment by Dalemal** [comment]
When I go to the comic Hager the Horrible I get the attached message. If I
try to go to see it in the browser it takes me to a different comic.

**Comment by kc2cbd** [comment]
I'm not seeing any issues either.

**Comment by oseparovic** [comment]
@Dalemal this is an old bug with the app that creeps up sometimes and is unrelated to specific comics. Open Hagar and click the 3 dot menu in the top right corner. Select "reset starting point". That should fix it.

**Comment by Dalemal** [comment]
That worked!!
Thanks so much
