### ISSUE TITLE
Zits comic not loading

### ISSUE THREAD

**Issue by LucyGlo** [oseparovic/comic_selectors#170]
When I tried to view Zits on July 17th and 18th, 2023, there was only the Image Not Found page with the link to view in the browser, Refresh, or or Report on GitHub. Refreshing had no effect. When I clicked the View in Browser link, it went to the page for Off the Mark, the previous comic I had viewed. Also, GoComics doesn't seem to have Zits listed.

**Comment by swapnilsarwe** [comment]
Hey @LucyGlo ,

Zits was removed from gocomics, but it is available on arcamax.com & i guess the appropriate changes were done to pick the strips from arcamax.com on PageFlip around 2 years ago.
