### ISSUE TITLE
App not loading 

### ISSUE THREAD

**Issue by kimo555555** [oseparovic/comic_selectors#186]
Cannot open my comics

**Comment by oseparovic** [comment]
Can you provide more details? Are you experiencing what is described here? 

https://github.com/oseparovic/comic_selectors/issues/182

**Comment by kimo555555** [comment]
Yes. Only Zits, Mutts & Baby Blues open in the phone app. All others need
to open in the browser, which is awful on my phone.

**Comment by oseparovic** [comment]
Please refer to the linked issue in my comment above. A patch should be out soon if it hasn't reached your region already

**Comment by kimo555555** [comment]
When is this patch supposed to be available? My comics still not opening,
and I deleted and reloaded PageFlip.

**Comment by oseparovic** [comment]
What device and Android version are you on?

**Comment by kimo555555** [comment]
Pixel 7 Pro
Version 14

**Comment by oseparovic** [comment]
If you have the app installed you should be able to go to the Google Play store page for it and see if there's an update (even though it's unpublished temporarily). 

The app version with the fix is 1.8.8
