### ISSUE TITLE
Blondie & Bloom Countie lead nowhere

### ISSUE THREAD

**Issue by swapnilsarwe** [oseparovic/comic_selectors#63]
This issue has been reported on [Google Play Store](https://play.google.com/store/apps/details?id=com.printandpixel.pageflip2&hl=en) on Jan 05, 2019.

It seems to be working as expected to me on PageFlip App - can someone confirm and close this issue?

And if anyone knows the owner - please comment on it for more details.

**Comment by oseparovic** [comment]
Duplicate selectors removed and bloom countie fixed as part of 06d0c80ce12d1bdf9de96f09a08961fccfda9790
