### ISSUE TITLE
Suggestion: add formatter for both json files

### ISSUE THREAD

**Issue by swapnilsarwe** [oseparovic/comic_selectors#82]
Hello @oseparovic ,

Should we add a formatter script which on every commit format the `supported_sites.json` & `featured.json`, to maintain the consistency.

**Comment by oseparovic** [comment]
Does git support doing this automatically? Otherwise this might be more trouble than it's worth as it can conflict with other pending commits

**Comment by swapnilsarwe** [comment]
I guess we can put up a github action to do it, will keep you updated on this.

**Comment by swapnilsarwe** [comment]
@oseparovic - hey recent github actions has given lot of abilities, now just user has to just push the changes.. formatting will be added automatically using github actions and create a new commit with formatted changes. I hope this comes handy and useful for all the maintainers of this repo.

**Comment by oseparovic** [comment]
Thanks for doing the research and integrating this. From a quick glance the workflow:"Node.js CI" is showing up in my action dashboard. Will close this issue for now and monitor how changes work 👍
