### ISSUE TITLE
Missing Preview Images

### ISSUE THREAD

**Issue by TheIgster** [oseparovic/comic_selectors#93]
The following comics that I follow are missing the preview images:

Adam@Home
Andy Capp
B.C.
Betty
Calvin & Hobbes
Dilbert
Foxtrot
Herman
Peanuts
Pearls Before Swine
Pickles
Shoe
The Duplex
Ziggy

**Comment by ComedyTomedy** [comment]
Turns out this affects a tonne of comics! It's because they've moved from http to https, and the image fetcher doesn't follow HTTP 3xx redirects.

A TONNE have changed, I'll submit a PR.
